# -*- coding: utf-8 -*-
"""Listes de prix officielles par metier (amorcage de la bibliotheque). DZD HT."""

PRIX_METIERS = {
    "Électricité": [
        ('Interrupteur simple', 800),
        ('Lampe / Point lumineux', 200),
        ('Interrupteur double', 1000),
        ('Sonnette / Cloche', 1500),
        ('Interrupteur va-et-vient', 1000),
        ('Boîte de dérivation', 800),
        ('Prise de courant', 800),
        ('Prise triphasée 380V', 2000),
        ('Prise avec mise à la terre', 900),
        ('Prise pour climatiseur', 1300),
        ('Prise TV / Coaxiale', 1500),
        ('Prise pour chauffe-eau / résistance', 1300),
        ('Prise RJ45 / Internet', 1500),
        ('Prise pour cuisinière / plaque', 1500),
        ('Bouton-poussoir pour télérupteur', 800),
        ('Détecteur de mouvement', 1500),
        ('Minuterie', 1000),
        ('Vidéophone', 5000),
        ('Cellule photoélectrique', 1000),
        ('Commande volet roulant', 1500),
        ('Bouton-poussoir sonnette', 800),
        ('Ventilateur / Extracteur', 1000),
        ('Tableau de protection (8 modules)', 4000),
        ('Tableau de protection (12 modules)', 6000),
        ('Tableau de protection (16 modules)', 8000),
        ('Tableau de protection (24 modules)', 10000),
        ('Tableau de protection (36 modules)', 12000),
        ('Lustre', 1000),
        ('Ruban LED (par mètre)', 200),
        ('Profilé LED (par mètre)', 800),
        ('Spot encastré avec câblage', 700),
        ('Pose spot seul', 400),
        ('Câblage / Distribution (par mètre)', 200),
        ('Disjoncteur général 220V', 1500),
        ('Disjoncteur général 380V', 2500),
        ("Système d'alarme anti-intrusion", 3000),
        ('Prise de courant + Terre', 900),
        ('Bouton-poussoir télérupteur', 800),
        ('Prise réseau RJ45', 1500),
        ('Prise téléphone (RJ11)', 1000),
        ('Vidéophone / Interphone', 5000),
        ('Tableau de protection 6 modules', 3000),
        ('Tableau de protection 10 modules', 5000),
        ('Tableau de protection 13 modules', 6500),
        ('Tableau de protection 24 modules', 12000),
        ('Tableau de protection 36 modules', 18000),
        ('Tableau de protection 48 modules', 24000),
        ('Ligne de terre (sans terrassement)', 5000),
        ('Ligne de terre (avec terrassement)', 8000),
        ('Pose spot seul (sans câblage)', 300),
    ],
}
